import type { NextRequest } from 'next/server';
import { taxInvoices } from '@/server/db/schema';
import { getLegacySession } from '@/server/auth/legacy-session';
import { withDb } from '@/server/db/client';
import { serverLegacyRequest } from '@/server/legacy-api';
import { resolveRequestTenant } from '@/server/request-tenant';

type Order = Record<string, any>;

function ascii(value: unknown) {
  return String(value ?? '')
    .replace(/[^\x20-\x7e]/g, '?')
    .slice(0, 180);
}

function escapePdf(value: unknown) {
  return ascii(value).replaceAll('\\', '\\\\').replaceAll('(', '\\(').replaceAll(')', '\\)');
}

/** Minimal dependency-free PDF. Thai glyphs are intentionally replaced until a licensed font is configured. */
function makePdf(lines: string[]) {
  const stream = `BT\n/F1 15 Tf\n50 790 Td\n${lines.map((line, index) => `${index ? '0 -24 Td\n' : ''}(${escapePdf(line)}) Tj`).join('\n')}\nET`;
  const objects = [
    '<< /Type /Catalog /Pages 2 0 R >>',
    '<< /Type /Pages /Kids [3 0 R] /Count 1 >>',
    '<< /Type /Page /Parent 2 0 R /MediaBox [0 0 595 842] /Resources << /Font << /F1 4 0 R >> >> /Contents 5 0 R >>',
    '<< /Type /Font /Subtype /Type1 /BaseFont /Helvetica >>',
    `<< /Length ${stream.length} >>\nstream\n${stream}\nendstream`,
  ];
  let pdf = '%PDF-1.4\n';
  const offsets = [0];
  for (let index = 0; index < objects.length; index += 1) {
    offsets.push(pdf.length);
    pdf += `${index + 1} 0 obj\n${objects[index]}\nendobj\n`;
  }
  const xref = pdf.length;
  pdf += `xref\n0 ${objects.length + 1}\n0000000000 65535 f \n`;
  for (let index = 1; index < offsets.length; index += 1)
    pdf += `${String(offsets[index]).padStart(10, '0')} 00000 n \n`;
  pdf += `trailer\n<< /Size ${objects.length + 1} /Root 1 0 R >>\nstartxref\n${xref}\n%%EOF`;
  return new TextEncoder().encode(pdf);
}

export async function GET(request: NextRequest, context: { params: Promise<{ orderId: string }> }) {
  const { orderId } = await context.params;
  const session = await getLegacySession();
  if (!session.customer && !session.admin)
    return Response.json({ ok: false, error: 'login_required' }, { status: 401 });

  let order: Order | undefined;
  try {
    if (session.admin) {
      const result = await serverLegacyRequest<{ orders?: Order[] }>('admin.orders.list');
      order = (result.orders || []).find(
        (item) => String(item.id) === orderId || String(item.order_no) === orderId,
      );
    } else {
      const result = await serverLegacyRequest<{ order?: Order }>('order.track', { order_no: orderId });
      order = result.order;
    }
  } catch {
    return Response.json({ ok: false, error: 'order_not_found' }, { status: 404 });
  }
  if (!order) return Response.json({ ok: false, error: 'order_not_found' }, { status: 404 });

  const tax = order.tax_invoice || {};
  const invoiceNo = `TAX-${String(order.order_no || order.id).slice(0, 48)}`;
  const total = Number(order.total || order.total_baht || 0);
  const tenant = resolveRequestTenant(request);
  if (tenant.ok && order.id) {
    await withDb((db) => db.insert(taxInvoices).values({
      tenantId: tenant.tenant.id,
      id: `invoice-${String(order.id).slice(0, 80)}`,
      orderId: String(order.id),
      invoiceNo,
      invoiceType: 'full_tax_invoice',
      customerName: String(tax.company_name || order.name || '-').slice(0, 180),
      taxId: String(tax.tax_id || '').slice(0, 32) || null,
      branch: String(tax.branch || '').slice(0, 80) || null,
      address: String(tax.address || order.address || '').slice(0, 1000) || null,
      subtotalSatang: Math.max(0, Math.round(Number(order.subtotal || 0) * 100)),
      vatSatang: Math.max(0, Math.round((total * 100 * 7) / 107)),
      totalSatang: Math.max(0, Math.round(total * 100)),
    }).onConflictDoNothing()).catch((error) => {
      console.warn('[invoice] relational record unavailable', error instanceof Error ? error.message : error);
    });
  }
  const lines = [
    'THAISERKIT SUPPLY',
    'TAX INVOICE / RECEIPT',
    `Invoice: ${invoiceNo}`,
    `Order: ${order.order_no || order.id}`,
    `Customer: ${tax.company_name || order.name || '-'}`,
    `Tax ID: ${tax.tax_id || '-'}`,
    `Address: ${tax.address || order.address || '-'}`,
    `Total (THB): ${total.toFixed(2)}`,
    '',
    'Generated by THAISERKIT SUPPLY. Please retain this document for tax records.',
  ];
  const body = makePdf(lines);
  return new Response(body, {
    headers: {
      'content-type': 'application/pdf',
      'content-disposition': `inline; filename="${invoiceNo.replace(/[^A-Za-z0-9_-]/g, '_')}.pdf"`,
      'cache-control': 'private, no-store',
    },
  });
}
